### PR TITLE
Added double quantization by default for int4 finetuning

### PR DESCRIPTION
**Pull request by binga**
This PR adds Double Quantization as a default to Int4 finetuning based on results in Table 3 in https://arxiv.org/pdf/2305.14314.pdf.

### CODE REVIEW

**Comment by psinger** [comment]
I dont see a comparison with not using DQ in that paper. Personally I would leave it at `False` by default.

**Comment by binga** [comment]
Any specific reason why DQ is being defaulted to `False`?

**Comment by psinger** [comment]
Because it is an extra setting that could potentially have side effects.
It is also False by default in HF
https://github.com/huggingface/transformers/blob/v4.32.1/src/transformers/utils/quantization_config.py#L173

We will add settings to enable it via https://github.com/h2oai/h2o-llmstudio/issues/374

**Comment by binga** [comment]
Understood, thank you for sharing additional context. Closing the PR.

**Pull request closed without merging**
