### PR TITLE
Fix IPO Loss

### PR DESCRIPTION
**Pull request by maxjeblick**
Fixes IPO loss implementation according to https://github.com/huggingface/trl/commit/29d439a2043edf4455b05cae5a1e2ade69d22794, see also https://huggingface.co/blog/pref-tuning

### CODE REVIEW

**Comment by gaborfodor** [comment]
I can not select `Beta` with the slider outside of [0.1, 0.5] range

**Comment by maxjeblick** [comment]
Good point, I increased the slider to `beta in [0, 1]`, 0.5 was set too conservative, probably.

**Review by gaborfodor — COMMENTED** [review]
Two tiny issues with tooltips in experiment settings:
* `Rejected Answer Column` does not have tooltip
* `Loss function` has the original sft tooltip
image

**Comment by maxjeblick** [comment]
Thanks, well spotted!

I've added a tooltip for rejected answers. For the loss function tooltip, there's already an [open issue](https://github.com/h2oai/h2o-llmstudio/issues/523). I'll look into this issue, tooltips are currently a bit diverging.

**Review by gaborfodor — APPROVED** [review]
Yeah, makes sense to fix the other tooltips together. Thanks @maxjeblick LGTM! I have run a few experiments the runs were stable and sometimes even better than DPO.

**Review by pascal-pfeiffer — APPROVED** [review]

**Pull request merged**
