### PR TITLE
fix generation_config for chat

### LINKED ISSUE #679: [BUG] Chat window generation parameters not updated
### 🐛 Bug

Result of https://github.com/h2oai/h2o-llmstudio/pull/646

Currently, chat window generation parameters are not updated as set on model level in `generation_config`

https://github.com/h2oai/h2o-llmstudio/blob/main/llm_studio/app_utils/sections/chat_update.py#L46
Is not doing anything anylonger

### PR DESCRIPTION
**Pull request by haqishen**
close #679

### CODE REVIEW

**Review by psinger — CHANGES_REQUESTED** [review]
Let's make this a utility function to pass a model config and a LLMS config and use it for both functions (creating backbone and there).

**Comment by haqishen** [comment]
> cbb964d

updated [cbb964d](https://github.com/h2oai/h2o-llmstudio/pull/682/commits/cbb964d45945b6859acd4d094ad3f58a62a4a810)

**Review by psinger — CHANGES_REQUESTED** [review]
overall lgtm

but for the prompt.py it will need to also update it after `cfg = parse_param(cfg, prompt)`
pelase make sure it works after adjusting

**Comment by haqishen** [comment]
> overall lgtm
> 
> but for the prompt.py it will need to also update it after `cfg = parse_param(cfg, prompt)` pelase make sure it works after adjusting

[cf17f05](https://github.com/h2oai/h2o-llmstudio/pull/682/commits/cf17f05f0aa593e0022cc16d81abd2b37140bc02)

check by
`--do_sample True`
`--temperature 0.5`
it works.

**Review by psinger — APPROVED** [review]
lgtm

**Pull request merged**
