### PR TITLE
Set huggingface token when loading tokenizers

### LINKED ISSUE #295: [BUG] Chatbot card broken for llama v2
### 🐛 Bug
Hugginface token is not set when loading the model in the app.
Thus, chat for llama v2 models (and probably other private models) fails with

`requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://huggingface.co/meta-llama/Llama-2-7b-chat-hf/resolve/main/tokenizer_config.json`

### PR DESCRIPTION
**Pull request by maxjeblick**
Fixes #295

### CODE REVIEW

**Review by pascal-pfeiffer — COMMENTED** [review]
thank you. Max

could you add the same when calling  `create_nlp_backbone`, maybe?

**Comment by maxjeblick** [comment]
> could you add the same when calling `create_nlp_backbone`, maybe?

Do we call this function somewhere within the app outside `load_cfg_model_tokenizer`?

**Comment by pascal-pfeiffer** [comment]
> Do we call this function somewhere within the app outside load_cfg_model_tokenizer?

it's the function that we call when initialising the model

**Comment by maxjeblick** [comment]
`load_cfg_model_tokenizer` will call `create_nlp_backbone` eventually, so that should be covered.

**Comment by maxjeblick** [comment]
For `train.py`, env variable is set when starting from the app, for cli usage you would need to set the env variable `HUGGINGFACE_TOKEN` explicitly.

**Comment by pascal-pfeiffer** [comment]
> For `train.py`, env variable is set when starting from the app, for cli usage you would need to set the env variable `HUGGINGFACE_TOKEN` explicitly.

right. That's where I missed it.

**Review by pascal-pfeiffer — APPROVED** [review]
thank you, lgtm!

**Pull request merged**
