### PR TITLE
HF friendly repo name

### PR DESCRIPTION
**Pull request by fatihozturkh2o**
As someone who is used to naming experiments and datasets with at least " " (spaces), I'm frequently running into a wrong naming error when I want to push a model to hf. (I can easily forget to rename it on the fly and it takes some time till hitting the error)

With this PR, I'm aiming for the ultimate first name suggestion that'll comply with all the HF naming rules 😄 

**Example**
Weird experiment name: **delete me we56rd chars...--as-**
HF-friendly suggestion: **delete-me-we56rd-chars-as**

### CODE REVIEW

**Review by pascal-pfeiffer — CHANGES_REQUESTED** [review]
Thank you! Great suggestion.

Could you please open an issue and link it to the PR, too?

Can we combine this with the already existing replacement for dots?

```python
q.client["experiment/display/experiment"].name.replace(".", "-"),
```

https://github.com/h2oai/h2o-llmstudio/blob/main/app_utils/sections/experiment.py#L1634

**Comment by fatihozturkh2o** [comment]
> Thank you! Great suggestion.
> 
> Could you please open an issue and link it to the PR, too?

done: https://github.com/h2oai/h2o-llmstudio/issues/327 

> Can we combine this with the already existing replacement for dots?
> 
> ```python
> q.client["experiment/display/experiment"].name.replace(".", "-"),
> ```
> 
> https://github.com/h2oai/h2o-llmstudio/blob/main/app_utils/sections/experiment.py#L1634

What do you mean by combining this with the existing replacement? The function I introduced is also replacing dots and I changed that line already in the PR 🤔

**Review by pascal-pfeiffer — APPROVED** [review]
> The function I introduced is also replacing dots and I changed that line already in the PR 🤔

I somehow missed that it is the same line... Great work, and thank you again. 

All lgtm!

**Comment by fatihozturkh2o** [comment]
> > The function I introduced is also replacing dots and I changed that line already in the PR 🤔
> 
> I somehow missed that it is the same line... Great work, and thank you again.
> 
> All lgtm!

👍 You can merge it maybe then, I'm not able to 😅

**Pull request merged**
