### PR TITLE
Bitsandbytes fixes

### PR DESCRIPTION
**Pull request by psinger**
Closes https://github.com/h2oai/h2o-llmstudio/issues/213

Recent BNB update introduced some extra keys in the state dicts without any tensor `weight_format`
need to filter them also when loading with float16

Also noticed another issue that int8 weights could also not be loaded anylonger because BNB hardcodes the same devices as is present in the weights file which for us always was cpu. So now I am taking the device specified in cfg to directly load the weights to the device.

### CODE REVIEW

**Review by maxjeblick — CHANGES_REQUESTED** [review]
Thanks a lot for the fixes!

Regarding the loading of the model weights, I observed increased peak GPU memory consumption (17404MiB on main vs. 30172MiB on this branch) when loading a model in the chat window.

**Comment by psinger** [comment]
Hmh thats strange, will need to investigate, thx.

**Comment by psinger** [comment]
Loading it on cpu seems better... otherwise it can need extra mem on GPU.
But then need to figure out the BNB issue... hard

**Review by maxjeblick — APPROVED** [review]
lgtm, thanks!

**Pull request merged**
