### PR TITLE
Generation config fix

### PR DESCRIPTION
**Pull request by psinger**
Discussion here:
https://github.com/h2oai/h2o-llmstudio/issues/240

### CODE REVIEW

**Comment by psinger** [comment]
Agree on the first suggestion, will change.

But we have the `load_cfg_model_tokenizer` helper function that should already make sure this is handled. Creating the tokenizer twice sounds inefficient to me.

**Comment by maxjeblick** [comment]
> But we have the load_cfg_model_tokenizer helper function that should already make sure this is handled. Creating the tokenizer twice sounds inefficient to me.

It does work with the existing codebase. Yet, it creates some additional entanglement across the codebase, e.g. I could not initialize `Model` class in isolation. As calling `get_tokenizer` introduces little computational overhead, I'd prefer this method.

**Comment by psinger** [comment]
ok I decided to take it from model config and make it transparent, wdyt? too much?

**Review by maxjeblick — APPROVED** [review]
Lgtm!

**Pull request merged**
