### PR TITLE
Allow to change branch for downloading huggingface models

### LINKED ISSUE #116: [FEATURE] Ability to specify model branch when reading in Hugging face models instead of just main
### 🚀 Feature

When trying to use a Korean based GPT, the models were stored on alternate branches and not the main branch. It would be great to be allowed to specify this in LLM studio. e.g. 

revision='KoGPT6B-ryan1.5b-float16'
Example backbone: https://huggingface.co/kakaobrain/kogpt/tree/KoGPT6B-ryan1.5b

### PR DESCRIPTION
**Pull request by haqishen**
close #116 

---

For example, setting like the following figure to use this branch：https://huggingface.co/kakaobrain/kogpt/tree/KoGPT6B-ryan1.5b

image

### CODE REVIEW

**Review by psinger — CHANGES_REQUESTED** [review]
LGTM!

I would suggest to move the setting though into the `Environment` section.

I dont think it will be regularly used - is a bit too prominent on top.
Let's call it `Huggingface LLM Backbone Branch` - or only `Huggingface Branch`.
And put it after trust remote code.

**Comment by haqishen** [comment]
Fixed in: [22d6fcc](https://github.com/h2oai/h2o-llmstudio/pull/168/commits/22d6fcc5f01028588dc873a6070484390397d78d)

**Review by psinger — APPROVED** [review]
lgtm - merge main in and then we can merge
thx

**Comment by psinger** [comment]
will take another look - just saw a strange error

**Review by psinger — CHANGES_REQUESTED** [review]
Maybe I spoke too soon, I get errors with the following backbones:

https://huggingface.co/openlm-research/open_llama_3b
https://huggingface.co/EleutherAI/pythia-1b

please check if they work for you

**Comment by psinger** [comment]
It works now, might have been an issue with HF.

Please double check though - thx!

**Comment by haqishen** [comment]
I checked and this worked : https://huggingface.co/openlm-research/open_llama_3b

But this does not: https://huggingface.co/EleutherAI/pythia-1b

```
File "/home/haqishen/src/h2o-llmstudio-my/llm_studio/src/datasets/text_utils.py", line 36, in get_tokenizer
tokenizer = AutoTokenizer.from_pretrained(
File "/home/haqishen/.local/share/virtualenvs/h2o-llmstudio-my-TDadbQEF/lib/python3.10/site-packages/transformers/models/auto/tokenization_auto.py", line 688, in from_pretrained
raise ValueError(
ValueError: Tokenizer class GPTNeoXTokenizer does not exist or is not currently imported.
```

Have you got this before?

**Comment by pascal-pfeiffer** [comment]
Yes, enable Fast Tokenizer

**Review by psinger — APPROVED** [review]
ok it is fine then, you can merge, thx

**Comment by haqishen** [comment]
I don't see merge button anywhere, maybe I don't have the privilege?

**Comment by psinger** [comment]
>This branch is out-of-date with the base branch
Merge the latest changes from main into this branch.

**Comment by haqishen** [comment]
image

Merged main to this branch. But still don't see merge button ↑

**Comment by psinger** [comment]
should work now

**Pull request merged**
